import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import { SliderData } from '../components/SliderData'
import Slider from '../components/Slider'
import Instagram from '../components/Instagram'


export default function Home() {
  return (
    <>
      <Head>
        <title>Illusion Tricking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero 
      heading='About Us' 
      message='Sports group based at the Event Center, Levin. We do a mixture of flips, kicks, and twists that create tricks! Classes run by Aaron Van Eijck.'
      frame='https://www.youtube.com/embed/GYfRuRT7fDY'
      />
      <Slider slides={SliderData} />
      <Instagram />
    </>
  )
}
